# Generated by Django 4.1.4 on 2022-12-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories', 'verbose_name_plural': 'category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'posts', 'verbose_name_plural': 'post'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tags', 'verbose_name_plural': 'tag'},
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
    ]
